//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPISzacho
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.comarch.pl/cdn/Products/CDN XL/", ConfigurationName="WebAPISzacho.CDNOffLineSrvSoap")]
    public interface CDNOffLineSrvSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comarch.pl/cdn/Products/CDN XL/ReceiveData", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAPISzacho.ReceiveDataResponse> ReceiveDataAsync(WebAPISzacho.ReceiveDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comarch.pl/cdn/Products/CDN XL/SendData", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAPISzacho.SendDataResponse> SendDataAsync(WebAPISzacho.SendDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comarch.pl/cdn/Products/CDN XL/ExecuteSQLCommand", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAPISzacho.ExecuteSQLCommandResponse> ExecuteSQLCommandAsync(WebAPISzacho.ExecuteSQLCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comarch.pl/cdn/Products/CDN XL/ExecuteSQLXmlCommand", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAPISzacho.ExecuteSQLXmlCommandResponse> ExecuteSQLXmlCommandAsync(WebAPISzacho.ExecuteSQLXmlCommandRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveData", Namespace="http://www.comarch.pl/cdn/Products/CDN XL/", Order=0)]
        public WebAPISzacho.ReceiveDataRequestBody Body;
        
        public ReceiveDataRequest()
        {
        }
        
        public ReceiveDataRequest(WebAPISzacho.ReceiveDataRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.comarch.pl/cdn/Products/CDN XL/")]
    public partial class ReceiveDataRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int oddzialID;
        
        public ReceiveDataRequestBody()
        {
        }
        
        public ReceiveDataRequestBody(int oddzialID)
        {
            this.oddzialID = oddzialID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveDataResponse", Namespace="http://www.comarch.pl/cdn/Products/CDN XL/", Order=0)]
        public WebAPISzacho.ReceiveDataResponseBody Body;
        
        public ReceiveDataResponse()
        {
        }
        
        public ReceiveDataResponse(WebAPISzacho.ReceiveDataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.comarch.pl/cdn/Products/CDN XL/")]
    public partial class ReceiveDataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ReceiveDataResult;
        
        public ReceiveDataResponseBody()
        {
        }
        
        public ReceiveDataResponseBody(byte[] ReceiveDataResult)
        {
            this.ReceiveDataResult = ReceiveDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendData", Namespace="http://www.comarch.pl/cdn/Products/CDN XL/", Order=0)]
        public WebAPISzacho.SendDataRequestBody Body;
        
        public SendDataRequest()
        {
        }
        
        public SendDataRequest(WebAPISzacho.SendDataRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.comarch.pl/cdn/Products/CDN XL/")]
    public partial class SendDataRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int oddzialID;
        
        public SendDataRequestBody()
        {
        }
        
        public SendDataRequestBody(byte[] data, int oddzialID)
        {
            this.data = data;
            this.oddzialID = oddzialID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendDataResponse", Namespace="http://www.comarch.pl/cdn/Products/CDN XL/", Order=0)]
        public WebAPISzacho.SendDataResponseBody Body;
        
        public SendDataResponse()
        {
        }
        
        public SendDataResponse(WebAPISzacho.SendDataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendDataResponseBody
    {
        
        public SendDataResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteSQLCommandRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteSQLCommand", Namespace="http://www.comarch.pl/cdn/Products/CDN XL/", Order=0)]
        public WebAPISzacho.ExecuteSQLCommandRequestBody Body;
        
        public ExecuteSQLCommandRequest()
        {
        }
        
        public ExecuteSQLCommandRequest(WebAPISzacho.ExecuteSQLCommandRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.comarch.pl/cdn/Products/CDN XL/")]
    public partial class ExecuteSQLCommandRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sqlCommand;
        
        public ExecuteSQLCommandRequestBody()
        {
        }
        
        public ExecuteSQLCommandRequestBody(string sqlCommand)
        {
            this.sqlCommand = sqlCommand;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteSQLCommandResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteSQLCommandResponse", Namespace="http://www.comarch.pl/cdn/Products/CDN XL/", Order=0)]
        public WebAPISzacho.ExecuteSQLCommandResponseBody Body;
        
        public ExecuteSQLCommandResponse()
        {
        }
        
        public ExecuteSQLCommandResponse(WebAPISzacho.ExecuteSQLCommandResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.comarch.pl/cdn/Products/CDN XL/")]
    public partial class ExecuteSQLCommandResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExecuteSQLCommandResult;
        
        public ExecuteSQLCommandResponseBody()
        {
        }
        
        public ExecuteSQLCommandResponseBody(string ExecuteSQLCommandResult)
        {
            this.ExecuteSQLCommandResult = ExecuteSQLCommandResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteSQLXmlCommandRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteSQLXmlCommand", Namespace="http://www.comarch.pl/cdn/Products/CDN XL/", Order=0)]
        public WebAPISzacho.ExecuteSQLXmlCommandRequestBody Body;
        
        public ExecuteSQLXmlCommandRequest()
        {
        }
        
        public ExecuteSQLXmlCommandRequest(WebAPISzacho.ExecuteSQLXmlCommandRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.comarch.pl/cdn/Products/CDN XL/")]
    public partial class ExecuteSQLXmlCommandRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sqlCommand;
        
        public ExecuteSQLXmlCommandRequestBody()
        {
        }
        
        public ExecuteSQLXmlCommandRequestBody(string sqlCommand)
        {
            this.sqlCommand = sqlCommand;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteSQLXmlCommandResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteSQLXmlCommandResponse", Namespace="http://www.comarch.pl/cdn/Products/CDN XL/", Order=0)]
        public WebAPISzacho.ExecuteSQLXmlCommandResponseBody Body;
        
        public ExecuteSQLXmlCommandResponse()
        {
        }
        
        public ExecuteSQLXmlCommandResponse(WebAPISzacho.ExecuteSQLXmlCommandResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.comarch.pl/cdn/Products/CDN XL/")]
    public partial class ExecuteSQLXmlCommandResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ExecuteSQLXmlCommandResult;
        
        public ExecuteSQLXmlCommandResponseBody()
        {
        }
        
        public ExecuteSQLXmlCommandResponseBody(byte[] ExecuteSQLXmlCommandResult)
        {
            this.ExecuteSQLXmlCommandResult = ExecuteSQLXmlCommandResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface CDNOffLineSrvSoapChannel : WebAPISzacho.CDNOffLineSrvSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class CDNOffLineSrvSoapClient : System.ServiceModel.ClientBase<WebAPISzacho.CDNOffLineSrvSoap>, WebAPISzacho.CDNOffLineSrvSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CDNOffLineSrvSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CDNOffLineSrvSoapClient.GetBindingForEndpoint(endpointConfiguration), CDNOffLineSrvSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CDNOffLineSrvSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CDNOffLineSrvSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CDNOffLineSrvSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CDNOffLineSrvSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CDNOffLineSrvSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAPISzacho.ReceiveDataResponse> WebAPISzacho.CDNOffLineSrvSoap.ReceiveDataAsync(WebAPISzacho.ReceiveDataRequest request)
        {
            return base.Channel.ReceiveDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAPISzacho.ReceiveDataResponse> ReceiveDataAsync(int oddzialID)
        {
            WebAPISzacho.ReceiveDataRequest inValue = new WebAPISzacho.ReceiveDataRequest();
            inValue.Body = new WebAPISzacho.ReceiveDataRequestBody();
            inValue.Body.oddzialID = oddzialID;
            return ((WebAPISzacho.CDNOffLineSrvSoap)(this)).ReceiveDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAPISzacho.SendDataResponse> WebAPISzacho.CDNOffLineSrvSoap.SendDataAsync(WebAPISzacho.SendDataRequest request)
        {
            return base.Channel.SendDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAPISzacho.SendDataResponse> SendDataAsync(byte[] data, int oddzialID)
        {
            WebAPISzacho.SendDataRequest inValue = new WebAPISzacho.SendDataRequest();
            inValue.Body = new WebAPISzacho.SendDataRequestBody();
            inValue.Body.data = data;
            inValue.Body.oddzialID = oddzialID;
            return ((WebAPISzacho.CDNOffLineSrvSoap)(this)).SendDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAPISzacho.ExecuteSQLCommandResponse> WebAPISzacho.CDNOffLineSrvSoap.ExecuteSQLCommandAsync(WebAPISzacho.ExecuteSQLCommandRequest request)
        {
            return base.Channel.ExecuteSQLCommandAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAPISzacho.ExecuteSQLCommandResponse> ExecuteSQLCommandAsync(string sqlCommand)
        {
            WebAPISzacho.ExecuteSQLCommandRequest inValue = new WebAPISzacho.ExecuteSQLCommandRequest();
            inValue.Body = new WebAPISzacho.ExecuteSQLCommandRequestBody();
            inValue.Body.sqlCommand = sqlCommand;
            return ((WebAPISzacho.CDNOffLineSrvSoap)(this)).ExecuteSQLCommandAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAPISzacho.ExecuteSQLXmlCommandResponse> WebAPISzacho.CDNOffLineSrvSoap.ExecuteSQLXmlCommandAsync(WebAPISzacho.ExecuteSQLXmlCommandRequest request)
        {
            return base.Channel.ExecuteSQLXmlCommandAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAPISzacho.ExecuteSQLXmlCommandResponse> ExecuteSQLXmlCommandAsync(string sqlCommand)
        {
            WebAPISzacho.ExecuteSQLXmlCommandRequest inValue = new WebAPISzacho.ExecuteSQLXmlCommandRequest();
            inValue.Body = new WebAPISzacho.ExecuteSQLXmlCommandRequestBody();
            inValue.Body.sqlCommand = sqlCommand;
            return ((WebAPISzacho.CDNOffLineSrvSoap)(this)).ExecuteSQLXmlCommandAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CDNOffLineSrvSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CDNOffLineSrvSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CDNOffLineSrvSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://serwer.szachownica.com.pl/cdnofflinesrv/cdnofflinesrv.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CDNOffLineSrvSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://serwer.szachownica.com.pl/cdnofflinesrv/cdnofflinesrv.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CDNOffLineSrvSoap,
            
            CDNOffLineSrvSoap12,
        }
    }
}
