// <auto-generated />
using Magazynier.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Magazynier.DataAccess.Migrations
{
    [DbContext(typeof(WarehouseProcessesContext))]
    [Migration("20210302200628_AddDocument")]
    partial class AddDocument
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Magazynier.DataAccess.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DclMagKod")
                        .HasColumnType("int");

                    b.Property<string>("Fmm_NrListu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fmm_NrlistuPaczka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trn_DataSkan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Trn_GidNumer")
                        .HasColumnType("int");

                    b.Property<int>("Trn_GidTyp")
                        .HasColumnType("int");

                    b.Property<string>("Trn_NrDokumentu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Trn_Stan")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("Magazynier.DataAccess.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Magazynier.DataAccess.Entities.Item", b =>
                {
                    b.HasOne("Magazynier.DataAccess.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });
#pragma warning restore 612, 618
        }
    }
}
